runtime: python37

handlers:
## static content routing
- url: /
  static_files: public/index.html
  upload: public/*
  secure: always

# hugo generates pages in directories so check for index.html first
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/*
  secure: always

- url: /
  static_dir: public/
  secure: always
