steps:

- name: klakegg/hugo:0.53-asciidoctor
  volumes:
  - name: public-assets
    path: /target
  args:
    - -F
    - --verbose

- name: gcr.io/cloud-builders/gcloud
  volumes:
  - name: public-assets
    path: /target
  entrypoint: bash
  args:
    - -c
    - |
      mkdir public && cp -r /target/* ./public/ && gcloud app deploy
