steps:

  - id: 'conditionally-build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - -c
    - |
      docker pull us.gcr.io/${PROJECT_ID}/${_APP_NAME}:${COMMIT_SHA} || \
      (docker build -t us.gcr.io/${PROJECT_ID}/${_APP_NAME}:${COMMIT_SHA} -t us.gcr.io/${PROJECT_ID}/${_APP_NAME}:latest . && \
      docker push us.gcr.io/${PROJECT_ID}/${_APP_NAME}:${COMMIT_SHA} && \
      docker push us.gcr.io/${PROJECT_ID}/${_APP_NAME}:latest)

  - id: 'get-kube-config'
    name: 'gcr.io/cloud-builders/kubectl'
    env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    - 'KUBECONFIG=/workspace/.kube/config'
    args: ['cluster-info']

  - id: 'deploy'
    name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    args:
      - helm
      - upgrade
      - --install
      - ${_APP_NAME}
      - --namespace=${_APP_NAME}
      - --set
      - imageTag=${COMMIT_SHA}
      - ./k8s/${_APP_NAME}

  - id: 'init'
    name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    args:
      - helm
      - init
      - --client-only

  - id: 'package-chart'
    name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    args:
      - helm
      - package
      - k8s/${_APP_NAME}

  - id: 'generate-index'
    name: 'gcr.io/$PROJECT_ID/cloud-builders-helm'
    env:
      - 'KUBECONFIG=/workspace/.kube/config'
    args:
      - helm
      - repo
      - index
      - .
      - --url
      - ${_HELM_REPO_URL}

  - id: 'sync-index'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - index.yaml
      - gs://${_HELM_REPO_GCS_BUCKET}/

  - id: 'sync-chart'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - cp
      - ${_APP_NAME}*.tgz
      - gs://${_HELM_REPO_GCS_BUCKET}/

